name: Create PR
description: |
  変更したファイルをコミットし、プルリクエストを作成します。
  プルリクエストのタイトルや本文には、コミットメッセージがそのまま利用されます。
  パーミッションに「contents: write」「pull-requests: write」が必要です。
inputs:
  message:
    required: true
    description: コミットメッセージ
outputs:
  branch:
    value:
    description: プルリクエストのブランチ

runs:
  using: composite
  steps:
    - id: pr
      shell: bash
      env:
        USERNAME: github-actions[bot]
        EMAIL: github-actions[bot]@users.noreply.github.com
        MESSAGE: ${{ inputs.message }}
        GITHUB_TOKEN: ${{ github.token }}
        BRANCH: auto/${{ github.run_id }}/${{ github.run_attempt }}
      run: |
        echo "branch=${BRANCH}" >> ${GITHUB_OUTPUT}
        git config --global user.name "${USERNAME}"
        git config --global user.email "{EMAIL}"
        git checkout -b "${BRANCH}"
        git add .
        git commit -m "${MESSAGE}"
        git push origin "${BRANCH}"
        gh pr create --head "${BRANCH}" --title "${MESSAGE}" --body "${MESSAGE}"
